/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;

import DAO.CategorieDAO;
import java.awt.HeadlessException;
import models.categorie;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import outils.DBConnection;
import outils.DBException;

/**
 *
 * @author bossmrpk
 */
public class CategoriePanel extends javax.swing.JPanel {

    DefaultTableModel model;
    CategorieDAO categorieDAO = new CategorieDAO();
    int idCategorieSelectionnee = -1;

    /**
     * Creates new form CategoriePanel
     */
    public CategoriePanel() {
        initComponents();
        chargerTableCategorie();
        ajouterEvenements();

        // --- DEBUT DE LA MODERNISATION ---
        // 1. Fond du panel principal (Gris clair de la maquette)
        this.setBackground(new java.awt.Color(242, 242, 242));

        // 2. Correction des titres (On remplace les bordures coupées par des labels)
        jLabel1.putClientProperty("FlatLaf.style", "font: semibold +10; foreground: #333333");

        // Style "Card" : Blanc, coins arrondis, et petite bordure grise
        String cardStyle = "arc: 20; background: #FFFFFF; border: 10,10,10,10,#FFFFFF";

        Formulaire.putClientProperty("FlatLaf.style", cardStyle);
        Table.putClientProperty("FlatLaf.style", cardStyle);

        // 3. Champs de saisie
        jLabel2.putClientProperty("FlatLaf.style", "font: semibold; foreground: #666666");
        textLibelle.putClientProperty("JTextField.placeholderText", "Nom de la catégorie...");
        textLibelle.putClientProperty("JComponent.roundRect", true);

        // 4. Correction du Tableau (Pour qu'il ne soit pas coupé)
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setViewportBorder(null);
        jTable1.setRowHeight(35);
        jTable1.setShowGrid(false);
        jTable1.putClientProperty("FlatLaf.style", "showHorizontalLines: true; intercellSpacing: 0,1; selectionBackground: #E8F0FE");

        // 5. Boutons style Maquette (Gris clair, texte sombre)
        String btnStyle = "arc: 10; background: #E0E0E0; foreground: #333333; font: bold; borderWidth: 0";
        AjouterBoutton.putClientProperty("FlatLaf.style", btnStyle);
        ModifierBoutton.putClientProperty("FlatLaf.style", btnStyle);
        SupprimerBoutton.putClientProperty("FlatLaf.style", btnStyle);
        NettoyerBoutton.putClientProperty("FlatLaf.style", btnStyle);

        // Force la mise à jour visuelle pour éviter les éléments coupés
        this.revalidate();
        this.repaint();
        // --- FIN DE LA MODERNISATION ---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Formulaire = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        textLibelle = new javax.swing.JTextField();
        AjouterBoutton = new javax.swing.JButton();
        SupprimerBoutton = new javax.swing.JButton();
        ModifierBoutton = new javax.swing.JButton();
        NettoyerBoutton = new javax.swing.JButton();
        Table = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setText("Gestion des Catégories");

        Formulaire.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nom des Categories");

        AjouterBoutton.setText("Ajouter");
        AjouterBoutton.addActionListener(this::AjouterBouttonActionPerformed);

        SupprimerBoutton.setText("Supprimer");
        SupprimerBoutton.addActionListener(this::SupprimerBouttonActionPerformed);

        ModifierBoutton.setText("Modifier");
        ModifierBoutton.addActionListener(this::ModifierBouttonActionPerformed);

        NettoyerBoutton.setText("Nettoyer");
        NettoyerBoutton.addActionListener(this::NettoyerBouttonActionPerformed);

        javax.swing.GroupLayout FormulaireLayout = new javax.swing.GroupLayout(Formulaire);
        Formulaire.setLayout(FormulaireLayout);
        FormulaireLayout.setHorizontalGroup(
            FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulaireLayout.createSequentialGroup()
                .addGroup(FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textLibelle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormulaireLayout.createSequentialGroup()
                        .addGroup(FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FormulaireLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addComponent(AjouterBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupprimerBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addGroup(FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModifierBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NettoyerBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                .addContainerGap())
        );
        FormulaireLayout.setVerticalGroup(
            FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulaireLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AjouterBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(FormulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupprimerBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NettoyerBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        Table.setBackground(new java.awt.Color(255, 255, 255));
        Table.setPreferredSize(new java.awt.Dimension(600, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nom des Categories"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table);
        Table.setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Formulaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Formulaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBouttonActionPerformed
        String libelle = textLibelle.getText();
        if (libelle.isEmpty() || !libelle.matches("[a-zA-ZÀ-ÿ\\s]+")) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer le nom de la categorie");
            return;
        }
        categorie cat = new categorie(0, libelle);

        try {
            categorieDAO.ajouter(cat);
            chargerTableCategorie();
            textLibelle.setText("");
            idCategorieSelectionnee = -1;
            JOptionPane.showMessageDialog(this,
                    "catégorie ajouter avec succès",
                    "succès",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | DBException e) {
            JOptionPane.showMessageDialog(this, "Erreur :" + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterBouttonActionPerformed

    private void SupprimerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBouttonActionPerformed
        if (idCategorieSelectionnee == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une categorie");
            return;
        }
        int confirmation = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cette catégorie ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (confirmation != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            categorieDAO.supprimer(idCategorieSelectionnee);
            chargerTableCategorie();
            textLibelle.setText("");
            idCategorieSelectionnee = -1;
            JOptionPane.showMessageDialog(this,
                    "catégorie supprimer avec succès",
                    "succès",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erreur :" + e.getMessage());
        } catch (DBException ex) {
            System.getLogger(CategoriePanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_SupprimerBouttonActionPerformed

    private void ModifierBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBouttonActionPerformed
        if (idCategorieSelectionnee == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une categorie");
            return;
        }
        String libelle = textLibelle.getText();
        if (libelle.isEmpty() || !libelle.matches("[a-zA-ZÀ-ÿ\\s]+")) {
            JOptionPane.showMessageDialog(this, "Le nom ne peut pas être vide !");
            return;
        }
        categorie cat = new categorie(idCategorieSelectionnee, libelle);
        try {
            categorieDAO.modifier(cat);
            chargerTableCategorie();
            textLibelle.setText("");
            idCategorieSelectionnee = -1;
            JOptionPane.showMessageDialog(this,
                    "catégorie modifier avec succès",
                    "succès",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | DBException e) {
            JOptionPane.showMessageDialog(this, "Erreur :" + e.getMessage());
        }

    }//GEN-LAST:event_ModifierBouttonActionPerformed

    private void NettoyerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NettoyerBouttonActionPerformed
        textLibelle.setText("");
        idCategorieSelectionnee = -1;
        jTable1.clearSelection();
        textLibelle.requestFocus();
        JOptionPane.showMessageDialog(this,
                "formulaire nettoyé");


    }//GEN-LAST:event_NettoyerBouttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterBoutton;
    private javax.swing.JPanel Formulaire;
    private javax.swing.JButton ModifierBoutton;
    private javax.swing.JButton NettoyerBoutton;
    private javax.swing.JButton SupprimerBoutton;
    private javax.swing.JPanel Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textLibelle;
    // End of variables declaration//GEN-END:variables

    private void chargerTableCategorie() {
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            List<categorie> liste = categorieDAO.lister();
            for (categorie cat : liste) {
                model.addRow(new Object[]{
                    cat.getId_categorie(),
                    cat.getLibelle()
                });
            }

        } catch (DBException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void ajouterEvenements() {

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int ligne = jTable1.getSelectedRow();
                if (ligne >= 0) {
                    idCategorieSelectionnee = (int) model.getValueAt(ligne, 0);
                    String libelle = model.getValueAt(ligne, 1).toString();
                    textLibelle.setText(libelle);
                }
            }
        });

// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
