/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

/**
 *
 * @author Xisclever
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
        this.setLocationRelativeTo(null); // centré à l'écran

        // Case à cocher admin — positionnée entre le password et le bouton
        javax.swing.JCheckBox chkAdmin = new javax.swing.JCheckBox("Compte administrateur");
        chkAdmin.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        chkAdmin.setBackground(getContentPane().getBackground());
        chkAdmin.setName("chkAdmin");
        chkAdmin.setBounds(38, 308, 250, 25); // ← juste sous le champ password
        getContentPane().add(chkAdmin);
        chkAdmin.getParent().setComponentZOrder(chkAdmin, 0); // ← passe au premier plan

        java.awt.Color bleuFonce = new java.awt.Color(11, 58, 102);
        java.awt.Color bleuBtn = new java.awt.Color(13, 79, 139);
        java.awt.Color blanc = new java.awt.Color(255, 255, 255);
        java.awt.Color grisClaire = new java.awt.Color(243, 244, 246);
        java.awt.Color grisTexte = new java.awt.Color(107, 114, 128);
        java.awt.Color texteSombre = new java.awt.Color(17, 24, 39);

        // Fond principal
        getContentPane().setBackground(grisClaire);

        // Titre
        jLabel1.setText("✎ Inscription");
        jLabel1.setForeground(bleuFonce);
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));

        // Sous-titre
        jLabel3.setForeground(grisTexte);
        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Labels champs
        jLabel4.setForeground(texteSombre);
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        jLabel5.setForeground(texteSombre);
        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // Champ login
        txtLogin.setBackground(blanc);
        txtLogin.setForeground(texteSombre);
        txtLogin.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(209, 213, 219), 1));
        txtLogin.putClientProperty("JTextField.placeholderText", "Choisissez un login...");

        // Champ password
        txtPassword.setBackground(blanc);
        txtPassword.setForeground(texteSombre);
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(209, 213, 219), 1));
        txtPassword.putClientProperty("JTextField.placeholderText", "Choisissez un mot de passe...");

        // Bouton S'inscrire
        btnLogin.setText("✚  Créer mon compte");
        btnLogin.setBackground(bleuBtn);
        btnLogin.setForeground(blanc);
        btnLogin.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnLogin.setOpaque(true);
        btnLogin.setFocusPainted(false);
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.putClientProperty("FlatLaf.style", "");

        // Lien retour login
        creerLienRetourLogin();

        this.revalidate();
        this.repaint();
    }

// Méthode pour ajouter un lien "Déjà un compte ?" dans RegisterView
    private void creerLienRetourLogin() {
        javax.swing.JLabel lblLogin = new javax.swing.JLabel("Déjà un compte ? Se connecter");
        lblLogin.setForeground(new java.awt.Color(13, 79, 139));
        lblLogin.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vue.LoginView loginPage = new vue.LoginView();
                new controller.LoginController(loginPage);
                loginPage.setVisible(true);
                dispose();
            }
        });

        // Ajout dans le layout — position sous le bouton
        getContentPane().setLayout(null); // garde AbsoluteLayout
        lblLogin.setBounds(55, 435, 280, 20);
        getContentPane().add(lblLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 24, 39));
        jLabel1.setText("INSCRIPTION");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 114, 128));
        jLabel3.setText("Système de gestion de restaurant");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 65, 81));
        jLabel4.setText("Login");

        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(17, 24, 39));
        txtLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 65, 81));
        jLabel5.setText("Password");

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(17, 24, 39));
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 26));

        btnLogin.setBackground(new java.awt.Color(153, 153, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(17, 24, 39));
        btnLogin.setText("S'inscrire");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(209, 213, 219), 1, true));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblMessage.setBackground(new java.awt.Color(220, 252, 231));
        lblMessage.setForeground(new java.awt.Color(22, 101, 52));
        lblMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 247, 208)));
        lblMessage.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 28, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel1)))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel3))
                        .addComponent(jLabel1))
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4)
                    .addGap(10, 10, 10)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel5)
                    .addGap(10, 10, 10)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 83, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    public javax.swing.JLabel getLblMessage() {
        return lblMessage;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMessage;
    public javax.swing.JTextField txtLogin;
    public javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JCheckBox chkAdmin;
}
