/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;
import controller.StatistiquesController;
import java.sql.SQLException;
import outils.DBException;

/**
 *
 * @author wilfried
 */
public class Statistics extends javax.swing.JPanel {

    /**
     * Creates new form statistics
     */
    public Statistics() throws DBException, SQLException {
        initComponents();
        // Empêche la sélection de dates après l'instant présent
        dateDebut.getJCalendar().setMaxSelectableDate(new java.util.Date());
        dateFin.getJCalendar().setMaxSelectableDate(new java.util.Date());
        StatistiquesController.ChiffreDay(ChiffreAffaireDay);
//        StatistiquesController.ChiffrePeriode(ChiffreAffairePeriod, dateDebut, dateFin);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        periode = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        datefin = new javax.swing.JLabel();
        dateDebut = new com.toedter.calendar.JDateChooser();
        datedebut = new javax.swing.JLabel();
        dateFin = new com.toedter.calendar.JDateChooser();
        revenuday = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ChiffreAffaireDay = new javax.swing.JLabel();
        revenuPeriod = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ChiffreAffairePeriod = new javax.swing.JLabel();
        meilleurVentes = new javax.swing.JPanel();
        meilleurVente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMeilVente = new javax.swing.JTable();
        prodSeuil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Statistiques");

        periode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Periode");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        datefin.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        datefin.setText("Date debut");

        datedebut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        datedebut.setText("Date Fin");

        javax.swing.GroupLayout periodeLayout = new javax.swing.GroupLayout(periode);
        periode.setLayout(periodeLayout);
        periodeLayout.setHorizontalGroup(
            periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(periodeLayout.createSequentialGroup()
                        .addGroup(periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(periodeLayout.createSequentialGroup()
                                .addComponent(datefin)
                                .addGap(514, 514, 514)
                                .addComponent(datedebut)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(periodeLayout.createSequentialGroup()
                        .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(dateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        periodeLayout.setVerticalGroup(
            periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datefin)
                    .addComponent(datedebut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        revenuday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Chiffre d'affaire du jour");

        ChiffreAffaireDay.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        ChiffreAffaireDay.setText("jLabel5");

        javax.swing.GroupLayout revenudayLayout = new javax.swing.GroupLayout(revenuday);
        revenuday.setLayout(revenudayLayout);
        revenudayLayout.setHorizontalGroup(
            revenudayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenudayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revenudayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChiffreAffaireDay)
                    .addComponent(jLabel3))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        revenudayLayout.setVerticalGroup(
            revenudayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenudayLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ChiffreAffaireDay)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        revenuPeriod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Chiffre d'affaire periodique");

        ChiffreAffairePeriod.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        ChiffreAffairePeriod.setText("jLabel7");

        javax.swing.GroupLayout revenuPeriodLayout = new javax.swing.GroupLayout(revenuPeriod);
        revenuPeriod.setLayout(revenuPeriodLayout);
        revenuPeriodLayout.setHorizontalGroup(
            revenuPeriodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenuPeriodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revenuPeriodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ChiffreAffairePeriod))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        revenuPeriodLayout.setVerticalGroup(
            revenuPeriodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenuPeriodLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(ChiffreAffairePeriod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        meilleurVentes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        meilleurVente.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        meilleurVente.setText("Meilleur ventes");

        listMeilVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Quantite vendu", "Prix Totale"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listMeilVente.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(listMeilVente);
        listMeilVente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout meilleurVentesLayout = new javax.swing.GroupLayout(meilleurVentes);
        meilleurVentes.setLayout(meilleurVentesLayout);
        meilleurVentesLayout.setHorizontalGroup(
            meilleurVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meilleurVentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meilleurVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(meilleurVentesLayout.createSequentialGroup()
                        .addComponent(meilleurVente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        meilleurVentesLayout.setVerticalGroup(
            meilleurVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meilleurVentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(meilleurVente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        prodSeuil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Produits sous seuil");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Stock Actuel", "Seuil Actuel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout prodSeuilLayout = new javax.swing.GroupLayout(prodSeuil);
        prodSeuil.setLayout(prodSeuilLayout);
        prodSeuilLayout.setHorizontalGroup(
            prodSeuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodSeuilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodSeuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(prodSeuilLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        prodSeuilLayout.setVerticalGroup(
            prodSeuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodSeuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prodSeuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meilleurVentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(periode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(revenuday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(revenuPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(revenuPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(revenuday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(meilleurVentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prodSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChiffreAffaireDay;
    private javax.swing.JLabel ChiffreAffairePeriod;
    private com.toedter.calendar.JDateChooser dateDebut;
    private com.toedter.calendar.JDateChooser dateFin;
    private javax.swing.JLabel datedebut;
    private javax.swing.JLabel datefin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listMeilVente;
    private javax.swing.JLabel meilleurVente;
    private javax.swing.JPanel meilleurVentes;
    private javax.swing.JPanel periode;
    private javax.swing.JPanel prodSeuil;
    private javax.swing.JPanel revenuPeriod;
    private javax.swing.JPanel revenuday;
    // End of variables declaration//GEN-END:variables

//    private void actualiserRevenuPeriodique() {
//    java.util.Date d1 = dateDebut.getDate();
//    java.util.Date d2 = dateFin.getDate();

//    if (d1 != null && d2 != null) {
//        try {
//            double chiffre = StatistiquesController.ChiffrePeriode(d1, d2);
//            labelPeriodRevenue.setText(String.format("%.2f $", chiffre));
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//    }
//}

}
