/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;

import controller.UtilisateurController;

/**
 *
 * @author agbeb
 */
public class Utilisateurs extends javax.swing.JPanel {

    /**
     * Creates new form Utilisateurs
     */
    public Utilisateurs() {
        initComponents();

        // 1. Titre Principal
        jLabel1.putClientProperty("FlatLaf.style", "font: semibold +8");

        // 2. Transformer le panel en "Carte" (Blanc, arrondi, bordure fine)
        String cardStyle = "arc: 15; background: #FFFFFF; border: 1,1,1,1,#E0E0E0";
        jPanel2.putClientProperty("FlatLaf.style", cardStyle);

        // 3. Style du Tableau (Comme sur la maquette)
        TableauUtilisateurs.setRowHeight(40); // Lignes plus hautes
        TableauUtilisateurs.putClientProperty("FlatLaf.style", "showHorizontalLines: true; intercellSpacing: 0,1; selectionBackground: #f5f5f5");
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // 4. Configurer les colonnes correctes (ID, Login, Mot de passe)
        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Login", "Mot de passe"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tableau en lecture seule
            }
        };
        TableauUtilisateurs.setModel(tableModel);
        TableauUtilisateurs.getColumnModel().getColumn(0).setMaxWidth(60);

        // 5. Chargement initial des données depuis la BDD
        UtilisateurController.remplirTableau(TableauUtilisateurs);
        // 4. Style des Boutons
        // Bouton Ajouter (Bleu foncé)

        // 4. Style des Boutons
        // Bouton Ajouter (Bleu foncé)
        jButton1.setBackground(new java.awt.Color(3, 79, 132));
        jButton1.setForeground(java.awt.Color.WHITE);
        jButton1.putClientProperty("JButton.buttonType", "roundRect");

        // Bouton Supprimer (Rouge contour)
        BoutonSupprimerUtilisateur.putClientProperty("JButton.buttonType", "roundRect");
        BoutonSupprimerUtilisateur.setBackground(java.awt.Color.WHITE);
        BoutonSupprimerUtilisateur.setForeground(new java.awt.Color(200, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableauUtilisateurs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BoutonSupprimerUtilisateur = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestion des Utilisateurs");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        TableauUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Utilisateurs", "Rôle", "Email"
            }
        ));
        jScrollPane1.setViewportView(TableauUtilisateurs);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter Utilisateur");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        BoutonSupprimerUtilisateur.setBackground(new java.awt.Color(255, 51, 51));
        BoutonSupprimerUtilisateur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BoutonSupprimerUtilisateur.setForeground(new java.awt.Color(242, 242, 242));
        BoutonSupprimerUtilisateur.setText("Supprimer Utilisateur");
        BoutonSupprimerUtilisateur.addActionListener(this::BoutonSupprimerUtilisateurActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BoutonSupprimerUtilisateur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BoutonSupprimerUtilisateur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UtilisateurController.ajouterUtilisateur(TableauUtilisateurs);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void BoutonSupprimerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSupprimerUtilisateurActionPerformed
        UtilisateurController.supprimerUtilisateur(TableauUtilisateurs);
    }//GEN-LAST:event_BoutonSupprimerUtilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSupprimerUtilisateur;
    private javax.swing.JTable TableauUtilisateurs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
